export const ActionTypes = {
    SEARCH_KEY: 'SEARCH_KEY',
    SET_STATE_LIST: 'SET_STATE_LIST',
    SET_DATE_STATE_LIST: 'SET_DATE_STATE_LIST',
    STATE_LIST: 'STATE_LIST',
    DATE_SEARCH: 'DATE_SEARCH',
    SET_LIST_DATA: 'SET_LIST_DATA',
}